name: Crocodile Bot Run

on:
  push:
    branches: [ "main" ]  # Kod main branchga yuklanganda ishga tushadi
  workflow_dispatch:      # Qo'lda (Run workflow tugmasi bilan) yoqish imkonini beradi

jobs:
  start-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: Pythonni sozlash
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kutubxonalarni o'rnatish
        run: |
          python -m pip install --upgrade pip
          pip install aiogram  # Sizning kodingiz uchun kerakli kutubxona

      - name: Botni ishga tushirish
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # GitHub Secrets'dan tokenni oladi
        run: python main.py
